---
zroot: "zroot/jocker"
volume_root: "zroot/jocker/volumes"

metadata_db: "/zroot/jocker/metadata.sqlite"
api_socket: "/var/run/jocker.sock"

base_layer_dataset: "zroot/jocker_basejail"

# Name of the interface that jocker creates and uses for its ip-addresses
network_if_name: "jocker0"

# Allocated block of ip-addresses available to jocker in cidr-format.
subnet: "10.20.30.40/24"
