---
zroot: "zroot/jocker"
volume_root: "zroot/jocker/volumes"

metadata_db: "/zroot/jocker/metadata.sqlite"
api_socket: "/var/run/jocker.sock"

base_layer_dataset: "zroot/jocker_basejail"

# Name of the loopback interface used for the default network
default_loopback_name: "jocker0"

# Allocated block of ip-addresses available to jocker in cidr-format.
default_subnet: "10.20.30.40/24"

# Default interface used as default gateway for containers.
# If not set Jocker will try to detect it automatically.
# default_gateway_if: "em0"
