---
# Root ZFS dataset where Jocker stores the images, containers and volumes. Must be set.
zroot: "zroot/jocker"

# Where jocker listens for commands. Must be set: tcp://[host]:[port][path] or unix://[/path/to/socket]
api_socket: "unix:///var/run/jocker.sock"

# Dataset containg the userland that is used to build images. Must be set.
base_layer_dataset: "zroot/jocker_basejail"

# Name of the default network. If omitted no default network is created.
default_network_name: "default"

# Name of the loopback interface used for the default network. If omitted 'jocker0' is used.
default_loopback_name: "jocker0"

# Subnet (in CIDR-format) allocated the default network. If omitted '172.17.0.0/16' is used.
default_subnet: "172.17.0.0/16"

# Default interface used as default gateway for containers. If omitted jocker tries to detect it automatically.
# default_gateway_if: "em0"
