---
# Root ZFS dataset where Kleened stores images, containers, and volumes. Must be set.
kleene_root: "zroot/kleene"

# Path to the template that is used to generate thee pf.conf(5) file for the host
pf_config_template_path: "/usr/local/etc/kleened/pf.conf.kleene"

# Path to the generated file that is loaded into pf(4)
pf_config_path: "/etc/pf.conf"

# Sockets where the kleened-API is listenening.
api_listening_sockets:
    ### TCP-socket using IPv4 using TLS _with_ client authentication and DH-parameters
    # The format is http[s]://[ip4|ip6][:port][/path/to/unix_socket].
    ### UNIX-socket without TLS without
    - address: "http:///var/run/kleened.sock"

# Log to /var/log/kleened.log
enable_logging: true

# Verbosity of logs on. Useful set of logging-values: debug, info, notice, warning, error, critical
# All Elixir levels: debug, info, notice, warning, error, critical, alert, emergency
# log_level: <value> is interpreted as "all messages that are <value> or worse"
log_level: "debug"
